// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace PMC.Data.DF.CustomerPortalOrchTest;

public partial class ResourceCategory
{
    public int ID { get; set; }

    public string Title { get; set; } = null!;

    public string? Description { get; set; }

    public int TypeID { get; set; }

    public virtual ICollection<Link> Links { get; set; } = new List<Link>();

    public virtual ICollection<ResourceDownload> ResourceDownloads { get; set; } = new List<ResourceDownload>();

    public virtual ICollection<ResourceFolder> ResourceFolders { get; set; } = new List<ResourceFolder>();

    public virtual ICollection<ResourceLink> ResourceLinks { get; set; } = new List<ResourceLink>();

    public virtual ResourceCategoryType Type { get; set; } = null!;
}