// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace PMC.Data.DF.CustomerPortalOrchTest;

public partial class ResourceFolder
{
    public int Id { get; set; }

    public string FolderName { get; set; } = null!;

    public int? ParentFolderId { get; set; }

    public int? CategoryId { get; set; }

    public virtual ResourceCategory? Category { get; set; }

    public virtual ICollection<ResourceFolder> InverseParentFolder { get; set; } = new List<ResourceFolder>();

    public virtual ResourceFolder? ParentFolder { get; set; }

    public virtual ICollection<ResourceDownload> ResourceDownloads { get; set; } = new List<ResourceDownload>();
}