// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace PMC.Data.DF.CustomerPortalOrchTest;

public partial class ResourceDownload
{
    public int ID { get; set; }

    public string Name { get; set; } = null!;

    public string? Description { get; set; }

    public string FilePath { get; set; } = null!;

    public int CategoryID { get; set; }

    public int? ThumbnailID { get; set; }

    public int? FolderId { get; set; }

    public virtual ResourceCategory Category { get; set; } = null!;

    public virtual ResourceFolder? Folder { get; set; }

    public virtual ResourceThumbnail? Thumbnail { get; set; }

    public virtual ICollection<ResourceTag> Tags { get; set; } = new List<ResourceTag>();
}