// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace PMC.Data.DF.CustomerPortal;

public partial class CustomerPortalContext : DbContext
{
    public CustomerPortalContext(DbContextOptions<CustomerPortalContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Link> Links { get; set; }

    public virtual DbSet<ResourceCategory> ResourceCategories { get; set; }

    public virtual DbSet<ResourceCategoryType> ResourceCategoryTypes { get; set; }

    public virtual DbSet<ResourceDownload> ResourceDownloads { get; set; }

    public virtual DbSet<ResourceFolder> ResourceFolders { get; set; }

    public virtual DbSet<ResourceLink> ResourceLinks { get; set; }

    public virtual DbSet<ResourceTag> ResourceTags { get; set; }

    public virtual DbSet<ResourceTagType> ResourceTagTypes { get; set; }

    public virtual DbSet<ResourceThumbnail> ResourceThumbnails { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Link>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK_ResourcesInfo.Links");

            entity.ToTable("Links", "ResourcesInfo");

            entity.HasOne(d => d.Category).WithMany(p => p.Links)
                .HasForeignKey(d => d.CategoryID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Links_ResourceCategories");
        });

        modelBuilder.Entity<ResourceCategory>(entity =>
        {
            entity.ToTable("ResourceCategories", "ResourcesInfo");

            entity.HasOne(d => d.Type).WithMany(p => p.ResourceCategories)
                .HasForeignKey(d => d.TypeID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ResourceCategories_ResourceCategoryTypes");
        });

        modelBuilder.Entity<ResourceCategoryType>(entity =>
        {
            entity.ToTable("ResourceCategoryTypes", "ResourcesInfo");
        });

        modelBuilder.Entity<ResourceDownload>(entity =>
        {
            entity.ToTable("ResourceDownloads", "ResourcesInfo");

            entity.HasOne(d => d.Category).WithMany(p => p.ResourceDownloads)
                .HasForeignKey(d => d.CategoryID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ResourceDownloads_ResourceCategories");

            entity.HasOne(d => d.Folder).WithMany(p => p.ResourceDownloads)
                .HasForeignKey(d => d.FolderId)
                .HasConstraintName("FK_ResourceDownloads_ResourceFolders");

            entity.HasOne(d => d.Thumbnail).WithMany(p => p.ResourceDownloads)
                .HasForeignKey(d => d.ThumbnailID)
                .HasConstraintName("FK_ResourceDownloads_ResourceThumbnails");

            entity.HasMany(d => d.Tags).WithMany(p => p.Resources)
                .UsingEntity<Dictionary<string, object>>(
                    "ResourceDownloadsXTag",
                    r => r.HasOne<ResourceTag>().WithMany()
                        .HasForeignKey("TagID")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK_ResourceDownloadsXTags_ResourceTags"),
                    l => l.HasOne<ResourceDownload>().WithMany()
                        .HasForeignKey("ResourceID")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK_ResourceDownloadsXTags_ResourceDownloads"),
                    j =>
                    {
                        j.HasKey("ResourceID", "TagID");
                        j.ToTable("ResourceDownloadsXTags", "ResourcesInfo");
                    });
        });

        modelBuilder.Entity<ResourceFolder>(entity =>
        {
            entity.ToTable("ResourceFolders", "ResourcesInfo");

            entity.HasOne(d => d.Category).WithMany(p => p.ResourceFolders)
                .HasForeignKey(d => d.CategoryId)
                .HasConstraintName("FK_ResourceFolders_ResourceCategories");

            entity.HasOne(d => d.ParentFolder).WithMany(p => p.InverseParentFolder)
                .HasForeignKey(d => d.ParentFolderId)
                .HasConstraintName("FK_ResourceFolders_ResourceFolders");
        });

        modelBuilder.Entity<ResourceLink>(entity =>
        {
            entity.ToTable("ResourceLinks", "ResourcesInfo");

            entity.HasOne(d => d.Category).WithMany(p => p.ResourceLinks)
                .HasForeignKey(d => d.CategoryID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ResourceLinks_ResourceCategories");
        });

        modelBuilder.Entity<ResourceTag>(entity =>
        {
            entity.ToTable("ResourceTags", "ResourcesInfo");

            entity.HasOne(d => d.Type).WithMany(p => p.ResourceTags)
                .HasForeignKey(d => d.TypeID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ResourceTags_ResourceTagTypes");
        });

        modelBuilder.Entity<ResourceTagType>(entity =>
        {
            entity.ToTable("ResourceTagTypes", "ResourcesInfo");
        });

        modelBuilder.Entity<ResourceThumbnail>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK_StandardThumbnails");

            entity.ToTable("ResourceThumbnails", "ResourcesInfo");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}