// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace PMC.Data.DF.CustomerPortal;

public partial class Link
{
    public int ID { get; set; }

    public string? Name { get; set; }

    public string? RelativePath { get; set; }

    public string? CsvRoles { get; set; }

    public int CategoryID { get; set; }

    public bool ShowInHeader { get; set; }

    public string? Description { get; set; }

    public string? FontAwesomeIcon { get; set; }

    public bool HideFromOldWebsite { get; set; }

    public virtual ResourceCategory Category { get; set; } = null!;
}