// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace PMC.Data.DF.CustomerPortal;

public partial class ResourceCategoryType
{
    public int ID { get; set; }

    public string TypeName { get; set; } = null!;

    public virtual ICollection<ResourceCategory> ResourceCategories { get; set; } = new List<ResourceCategory>();
}