// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace PMC.Data.DF.CustomerPortal;

public partial class ResourceTagType
{
    public int ID { get; set; }

    public string Name { get; set; } = null!;

    public virtual ICollection<ResourceTag> ResourceTags { get; set; } = new List<ResourceTag>();
}