// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace PMC.Data.DF.CustomerPortal;

public partial class ResourceTag
{
    public int ID { get; set; }

    public string Name { get; set; } = null!;

    public int TypeID { get; set; }

    public virtual ResourceTagType Type { get; set; } = null!;

    public virtual ICollection<ResourceDownload> Resources { get; set; } = new List<ResourceDownload>();
}