// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace PMC.Data.DF.CustomerPortal;

public partial class ResourceLink
{
    public int ID { get; set; }

    public string Name { get; set; } = null!;

    public string Description { get; set; } = null!;

    public string URL { get; set; } = null!;

    public int CategoryID { get; set; }

    public virtual ResourceCategory Category { get; set; } = null!;
}