// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace PMC.Data.DF.CustomerPortal;

public partial class ResourceThumbnail
{
    public int ID { get; set; }

    public string Name { get; set; } = null!;

    public string FilePath { get; set; } = null!;

    public virtual ICollection<ResourceDownload> ResourceDownloads { get; set; } = new List<ResourceDownload>();
}